### ISSUE TITLE
SubContainer compatibility

### ISSUE THREAD

**Issue by BaalEvan** [drannex42/vivaldi-mods#1]
Great mod! 
But this new subContainer is really big QoL for me so i made something like compatibility for it.

its very rough because I'm not experienced at all with JS so you should rewrite it :P 

```js
//Add listener to OnTabChanged/Updated to check if state of subContainer chaned
  chrome.tabs.onUpdated.addListener(function(tabId, changeInfo, tab) {
    var subcont = document.getElementById("tabs-subcontainer");
    var browser = document.getElementById("browser");
    
    console.log("onTabChange");
    
    if(subcont.className === "right visible"){
        browser.classList.add("subVisible");
    }else{
        browser.classList.remove("subVisible");
    }
      
  });
  
//Add listener to OnActivated because change of focus clears classes on browser
  vivaldi.windowPrivate.onActivated.addListener(function(){var subcont = document.getElementById("tabs-subcontainer");
  var browser = document.getElementById("browser");
  
  console.log("onTabChange");
  
  if(subcont.className === "right visible"){
      browser.classList.add("subVisible");
  }else{
      browser.classList.remove("subVisible");
  }});
```

css changes
```css

#tabs-subcontainer{
    flex-basis: 170px;
    margin-top: 58px;
    background: transparent;
    margin-right: 50px;
    border: none;
    box-shadow: none;

}
/*Not move webView if there is no subvisible on browser or if browser is full screen
.subVisible:not(.fullscreen) #webview-container {
    margin-right: 50px;
}
#tabs-subcontainer.right:hover {
    position: fixed;
    left: 0;
    z-index: 9999999;
    color: var(--colorFg) !important;
    background-color: var(--colorBg);
    height: 100%;
    top: 0;
    width: 250px !important;
    padding-top: 25px;
}
#tabs-subcontainer.right:hover{
    right: 0px !important;
    left: auto !important;
}
#tabs-subcontainer.right .button-toolbar.newtab{
    flex-direction: row-reverse;
    text-align: right;
}
#tabs-subcontainer.right .tab-header {
    flex-direction: row-reverse;
}
#tabs-subcontainer.left:not(:hover),
#tabs-subcontainer.right:not(:hover) {
    width: 50px !important;
    height: 100%;
    position: fixed;
    background-color: var(--colorBgAlpha);
    top: 0;
    left: 0;
    padding-top: 25px;
}
#tabs-subcontainer.right:not(:hover)  {
    right: 0px !important;
    left: auto !important;
}
```
![Gif](https://i.imgur.com/PXg2041.gif)
